version: '3.8'
services:
  airflow-orchestrator:
    build: .
    container_name: log-airflow-orchestrator
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/airflow/data
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: standalone
